#-   name: grafana group
    #group:
        #name: grafana

#-   name: grafana user
    #user:
        #name: grafana
        #group: grafana

-   name: download grafana
    get_url:
        url: "{{ grafana_release_url }}"
        dest: "{{ grafana_release_filename }}"

-   name: install grafana
    apt:
        deb: "{{ grafana_release_filename }}"

-   fail:
-   name: extract grafana binary
    args:
        creates: /usr/local/bin/grafana
    shell: |
        tar --extract \
            --strip-components=1 \
            --wildcards \
            --file "{{ grafana_release_filename }}" \
            --directory /usr/local/bin/ \
            grafana*/grafana
-   name: grafana systemd unit
    copy:
        content: "{{ grafana_systemd_unit }}"
        dest: /etc/systemd/system/grafana.service
    notify:
    -   systemctl daemon-reload
    -   grafana rolling restart

-   name: /etc/grafana
    file: 
        path: /etc/grafana
        state: directory
-   name: /data/grafana
    file: 
        path: /data/grafana
        state: directory
        owner: grafana
        group: root
-   name: /etc/grafana/grafana.yml
    copy:
        content: "{{ grafana_config }}"
        dest: /etc/grafana/grafana.yml
        owner: root
        group: grafana
    notify: grafana rolling restart

-   name: start, enable grafana
    service:
        name: grafana
        state: started
        enabled: yes
