-   name: download grafana
    get_url:
        url: "{{ grafana_release_url }}"
        dest: "{{ grafana_release_filename }}"

-   name: install grafana
    apt:
        deb: "{{ grafana_release_filename }}"

-   name: /etc/grafana/grafana.ini
    copy:
        content: "{{ grafana_config }}"
        dest: /etc/grafana/grafana.ini
    notify: grafana rolling restart

-   name: /etc/grafana/ldap.toml
    when: grafana_ldap_config is defined
    copy:
        content: "{{ grafana_ldap_config }}"
        dest: /etc/grafana/ldap.toml
    notify: grafana rolling restart

-   name: start, enable grafana
    service:
        name: grafana-server
        state: started
        enabled: yes
