-   hosts: grafana
    gather_facts: no
    roles:
    -   role: grafana
    pre_tasks:
    -   name: allow local login for grafana user
        blockinfile:
            dest: /etc/security/access.conf
            block: |
                +:grafana:LOCAL
            insertbefore: BOF
