-   hosts: prometheus
    gather_facts: no
    roles:
    -   role: prometheus
    vars:
        prometheus_config: |
            global:
                scrape_interval: 30s
                evaluation_interval: 30s
            scrape_configs:
            -   job_name: node
                openstack_sd_configs:
                -   role: instance
                    identity_endpoint: {{ openstack_auth_url }}
                    region: RegionOne
                    userid: {{ prometheus_openstack_discovery_user_id }}
                    password: {{ prometheus_openstack_discovery_password }}
                    project_id: {{ openstack_project_id }}
                    port: 9100
                    refresh_interval: 1m
                    tls_config:
                        insecure_skip_verify: yes
                relabel_configs:
                #-   source_labels: [__meta_openstack_instance_status]
                    #action: keep
                    #regex: ACTIVE
                -   source_labels: [__meta_openstack_tag_prometheus_scrape]
                    action: keep
                    regex: 'true'
                -   regex: [__meta_openstack_tag_prometheus_custom_threshold_(.*)]
                    replacement: $1
            rule_files:
            -   /etc/prometheus/prometheus.rules.yml
        prometheus_rules: |
            groups:
            -   name: caccamo
                rules:
                {% raw %}
                -   alert: HostHighCpuLoad
                    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
                    for: 0m
                    labels:
                        severity: warning
                    annotations:
                        summary: |
                            Host high CPU load (instance {{ $labels.instance }})
                        description: |
                            CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}
                {% endraw %}
    pre_tasks:
    -   name: allow local login for prometheus user
        blockinfile:
            dest: /etc/security/access.conf
            block: |
                +:prometheus:LOCAL
            insertbefore: BOF
