-   hosts: prometheus
    gather_facts: no
    vars:
        prometheus_openstack_scrape_interval: 10s
        prometheus_openstack_evaluation_interval: 10s
    roles:
    -   role: prometheus_openstack
    pre_tasks:
    -   name: allow local login for prometheus user
        blockinfile:
            dest: /etc/security/access.conf
            block: |
                +:prometheus:LOCAL
            insertbefore: BOF
