-   hosts: prometheus
    gather_facts: no
    roles:
    -   role: prometheus
        
    vars:
        prometheus_openstack_scrape_interval: 30s
        prometheus_openstack_evaluation_interval: 30s
        prometheus_rules: |
            groups:
            -   name: caccamo
                rules:
                {% raw %}
                -   alert: HostHighCpuLoad
                        : |
                        100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
                    #100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > {{ $labels.cane }}
                    for: 0m
                    labels:
                        severity: warning
                    annotations:
                        summary: |
                            Host high CPU load (instance {{ $labels.instance }})
                        description: |
                            CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}
                {% endraw %}
    pre_tasks:
    -   name: allow local login for prometheus user
        blockinfile:
            dest: /etc/security/access.conf
            block: |
                +:prometheus:LOCAL
            insertbefore: BOF
