global:
    scrape_interval: {{ prometheus_openstack_scrape_interval }}
    evaluation_interval: {{ prometheus_openstack_scrape_interval }}
scrape_configs:
{% for c in prometheus_openstack_job_configs %}
-   job_name: {{ c.name }}
    openstack_sd_configs:
    -   role: instance
        identity_endpoint: {{ prometheus_openstack_auth_url }}
        region: RegionOne
        userid: {{ prometheus_openstack_user_id }}
        password: {{ prometheus_openstack_user_password }}
        project_id: {{ prometheus_openstack_project_id }}
        port: {{ c.port }}
        refresh_interval: {{ c.refresh_interval }}
        tls_config:
            insecure_skip_verify: yes
    relabel_configs:
    -   source_labels:
        -   __meta_openstack_tag_{{ c.openstack_tag_filter }}
        action: keep
        regex: 'true'
{% if c.name_as_instance %}
    -   source_labels: [__meta_openstack_instance_name]
        target_label: instance
{% endfor %}
