-   name: systemctl daemon-reload
    shell: systemctl daemon-reload

-   name: grafana rolling restart
    loop: "{{ play_hosts }}"
    loop_control:
        loop_var: rolling_restart_node
    include_tasks: tasks/rolling_restart_node.yml
