global:
    scrape_interval: {{ prometheus_openstack_scrape_interval }}
    evaluation_interval: {{ prometheus_openstack_scrape_interval }}
scrape_configs:
-   job_name: node_exporter
    openstack_sd_configs:
    -   role: instance
        identity_endpoint: {{ openstack_auth_url }}
        region: RegionOne
        userid: {{ prometheus_openstack_discovery_user_id }}
        password: {{ prometheus_openstack_discovery_password }}
        project_id: {{ openstack_project_id }}
        port: 9100
        refresh_interval: 10s
        tls_config:
            insecure_skip_verify: yes
    relabel_configs:
    -   source_labels: [__meta_openstack_instance_name]
        target_label: instance
    -   source_labels: [__meta_openstack_tag_prometheus_scrape_node]
        action: keep
        regex: 'true'
rule_files:
-   /etc/prometheus/prometheus.rules.yml
