global:
    scrape_interval: {{ prometheus_openstack_scrape_interval }}
    evaluation_interval: {{ prometheus_openstack_evaluation_interval }}
scrape_configs:

-   job_name: dynamic-0
    static_configs:
    -   targets:
        -   127.0.0.10:8080
    openstack_sd_configs:
    -   role: instance
        identity_endpoint: {{ openstack_auth_url }}
        region: RegionOne
        userid: {{ prometheus_openstack_discovery_user_id }}
        password: {{ prometheus_openstack_discovery_password }}
        project_id: {{ openstack_project_id }}
        port: 9100
        refresh_interval: 10s
        tls_config:
            insecure_skip_verify: yes
    relabel_configs:
    #-   source_labels: [__meta_openstack_tag_prometheus_io_scrape_0_address]
        #target_label: __address__
    -   source_labels: [__meta_openstack_tag_prometheus_io_scrape_0_name]
        target_label: __job_name__
        replacement: cane
    -   source_labels: [__meta_openstack_tag_prometheus_io_scrape_0_name]
        replacement: cane
        target_label: test
rule_files:
-   /etc/prometheus/prometheus.rules.yml
